# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'cgm-project-2-sonarcloud'
    organization: '1909-sep30-net'
    scannerMode: 'MSBuild'
    projectKey: 'cgm-project2'
    extraProperties: |
        sonar.exclusions=**/lib/**


- script: dotnet build ./cgm-project2 --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'
    projects: './cgm-project2'
    arguments: --configuration $(buildConfiguration) --settings **/coverletArgs.runsettings

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'

- task: SonarCloudAnalyze@1
  displayName: Sonar Analyze

- task: SonarCloudPublish@1
  displayName: Sonar Publish



- task: DotNetCoreCLI@2
  displayName: dotnet publish + zip
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: true

